name: Build and Deploy Blazor Golf API

on:
  workflow_dispatch:
  
  push:
    branches: [ main ]
    paths:
      - 'src/BlazorGolf.Api/**'

env:
  CONFIGURATION: Debug 
  API_PROJECT_PATH: './src/BlazorGolf.Api'   
  API_TESTS_PATH: './tests/ApiTests'   
  API_OUTPUT_PATH: './dist'      

jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
 
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      shell: bash
      run: |
        pushd './${{ env.API_PROJECT_PATH }}'
        dotnet build --configuration ${{ env.CONFIGURATION }}
        dotnet publish -c ${{ env.CONFIGURATION }} -o ${{env.API_OUTPUT_PATH}} 
        popd      
      
    - name: Test
      shell: bash
      run: |
        pushd './${{ env.API_TESTS_PATH }}'
        dotnet test --configuration ${{ env.CONFIGURATION }}      
        popd

  deploy_api:
    runs-on: ubuntu-latest
    needs: build_api

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name : 'dist'

    - name: Deploy to Azure Web App
      uses: actions/webapps-deploy@v2
      with:
        app-name: 'blazor-golf-api'
        publish-profile: '${{ secrets.DEV_AZURE_WEBAPI_PUBLISH_PROFILE }}'
